# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'PAUL SEO'
tagline:          'Blog'
description:      "Paul Seo<br> Landscape & Travel Photography<br>"
url:              http://neocur.github.io

author:
  name:           'Paul Seo'
  url:            https://twitter.com/neocur

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/neocur
